version: "3.3"
services:

  db: # service name
    image: postgres:latest # describes image the db service will use.
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/var/lib/postgresql/data
    expose:
      - 5432
  backend:
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432/sucuri
    build:
      context: ./
      dockerfile: Dockerfile
    command: poetry run uvicorn sucuri.asgi:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8009:8000